### ISSUE TITLE
Problems with the development version of tibble

### ISSUE THREAD

**Issue by krlmlr** [elbersb/segregation#1]
I'm in the process of preparing the release for _tibble_ 2.0.0. The _segregation_ package suggests _tibble_.

I'm seeing errors when testing your package with the dev version of _tibble_. 
We never fully supported row names, and now remove row names when creating or converting to a tibble. From what I saw, your package seems to rely on row names still being around after conversion to tibble. Unfortunately, a first pass of checking all downstream dependencies did not catch this problem.

Could you please install the development version of _tibble_ and run the tests in your package, so that we get a better understanding of the problem?

See https://www.tidyverse.org/articles/2018/11/tibble-2.0.0-pre-announce/ for details on the upcoming release.

**Comment by elbersb** [comment]
Thanks for letting me know.
Is there a good reason for removing the row names on conversion (i.e. deliberately removing information that the data frame contains but the tibble does not?) If tibble no longer support row names, I would remove the tibble-related functionality from the package and simply return a data frame.

**Comment by krlmlr** [comment]
Row names are not part of a tibble, keeping them would raise false expectations. Would you consider to convert to an explicit column instead, using the `rownames` argument to `as_tibble()` ?

**Comment by elbersb** [comment]
> Row names are not part of a tibble

Well -- they are right now, of course. I understand the desire to simplify code, but if there are still breaking changes in tibble, then it's probably better not to depend on it for package development.

The point is to provide easy access to well-known rows in the data frame, e.g. `mutual_total(schools00, "race", "school", weight = "n")[["M", "est"]]`. The row names are already an explicit column in the data frame/tibble, but then access is not as easy. Something like `mutual_total(schools00, "race", "school", weight = "n") %>% filter(stat == "M") %>% pull(est)` (what I think would be the tidyverse-way to do this) is less convenient.

I like the access by row names, so I'll remove the tibble dependency.

**Comment by krlmlr** [comment]
Thanks, I appreciate your help. Unfortunately, a first pass of checking all downstream dependencies did not catch this problem, otherwise you may have received an earlier notification. _tibble_ is generally stable, we try to reduce the amount of breaking changes to a minimum. We have updated https://tibble.tidyverse.org/dev/reference/index.html to include information on the "life cycle" status of each function.

For convenient access, you might be able to use an intermediate variable or an accessor function here. If you prefer plain data frames that's fine with me too.
