### ISSUE TITLE
Decompose differences in local segregation over time

### ISSUE THREAD

**Issue by JustinVisagie** [elbersb/segregation#11]
Hi Ben,

Thanks very much for a really useful (and well documented!) segregation package. I'd like to look at changes in **_local_** segregation scores over time but decomposed so that they become 'net of margins'. You have a neat example of this in your [paper](https://journals.sagepub.com/doi/10.1177/0049124121986204) but I'm struggling to see how to properly code for this. Do you perhaps have an example of your coding using your segregation package? 

Thanks so much,
Justin

**Comment by elbersb** [comment]
this has come up before, so I added an item to the FAQ https://elbersb.github.io/segregation/articles/faq.html#how-can-i-compute-margins-adjusted-local-segregation-scores

hope that helps!

**Comment by JustinVisagie** [comment]
Much appreciated!
