### ISSUE TITLE
Calculate Local segregation (ls) based on H?

### ISSUE THREAD

**Issue by jkaucic** [elbersb/segregation#14]
Is it possible to calculate Local segregation (ls) based on Theil’s Information Index (H) rather than on M?

**Comment by elbersb** [comment]
This comes up from time to time so I added an item to the FAQ here: https://elbersb.github.io/segregation/articles/faq.html#can-i-compute-local-segregation-scores-for-the-h-index

**Comment by jkaucic** [comment]
Thank you very much!
