### ISSUE TITLE
Test failure with dev testthat

### ISSUE THREAD

**Issue by hadley** [elbersb/segregation#4]
This test now fails: https://github.com/elbersb/segregation/blob/master/tests/testthat/test_mutual_total.R#L19-L23

It looks like you've accidentally supplied three arguments to `expect_equal()`.

**Comment by elbersb** [comment]
fixed -- I'll probably do a CRAN release within the next week or so

**Comment by hadley** [comment]
Thanks! (But no rush since dev testthat is at least >60 days out)
